services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  redis:
    ports: !reset []

  web:
    build:
      dockerfile: Dockerfile.prod
