services:
  db:
    image: postgres
    volumes:
      - ./var/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

#  web-deps:
#    build:
#      context: ~/PycharmProjects/django_base

  web:
    stdin_open: true
    tty: true
    build:
      context: .
      additional_contexts:
        # If building from local, editable source:
        django_base: ~/PycharmProjects/django_base
    volumes:
      - .:/code
      - ~/PycharmProjects/django_base:/python_local/django_base
    ports:
      - "8000:8000"
    depends_on:
      - db

#volumes:
#  django_base:
#    driver: local
#    driver_opts:
#      type: none
#      device: C:/Users/supra/PycharmProjects/django_base
#      o: bind

secrets:
  postgres_password:
    file: ./etc/postgres.txt
